### ISSUE TITLE
HTTP plugin open file leak

### ISSUE THREAD

**Issue by wattanakorn495** [iegomez/mosquitto-go-auth#22] opened 2019-06-16 05:46 UTC
the mosquitto log show too many file open

then i try counting open file in /proc/'PID'/fd 
using this command ""watch -n 0.5 "ls -l | wc -l"
and found that when broker get new client connection, opened file increase by 3 (maybe from GetUser, GetSuperuser and CheckAcl ) and when the client disconnect, opened file reduce only 1 

and i try change "return httpRequest..." to "return true"
the problem is solved

it may have some bug in httpRequest function

**Comment by iegomez** [comment] 2019-06-17 16:57
Thanks for reporting this. I'll give it a look and try to fix it as soon as possible.

**Comment by iegomez** [comment] 2019-06-17 19:09
I haven't been able to reproduce this. Are you sure it's the plugin the one not returning the file descriptors and not something else? Are you testing this against an HTTP service in the same machine which could potentially be the culprit?

**Comment by wattanakorn495** [comment] 2019-06-22 15:36
@iegomez 
sorry for late response

i solved it by moving htpp client and http transport into HTTP struct 

```go
type HTTP struct {
	UserUri      string
	SuperuserUri string
	AclUri       string
	Host         string
	Port         string
	WithTLS      bool
	VerifyPeer   bool
	ParamsMode   string
	ResponseMode string

	Client    *h.Client
	Transport *h.Transport
}
```

and initialize inside NewHTTP

```go
	tr := &h.Transport{ 
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	client := &h.Client{Timeout: 5 * time.Second}
	client.Transport = tr
	//Initialize with defaults
	var http = HTTP{
		WithTLS:      false,
		VerifyPeer:   false,
		ResponseMode: "status",
		ParamsMode:   "json",
		Transport:    tr,
		Client:       client,
	}
```

**Comment by mnezerka** [comment] 2020-01-04 21:59
Hi all, I see issue is closed, but no there is no fix in codebase. I see same behavior as @wattanakorn495. Mosquitto consumes all sockets (~54K) and is not able to open any HTTP requests towards authentication HTTP service. What was the reason for closing this issue, please?

**Comment by iegomez** [comment] 2020-01-06 19:09
It was closed by the OP because he found a solution. As I wasn't able to reproduce the problem, I didn't make any changes to the code. I'm opening the issue again in case you can provide any more details on the error.

**Comment by mnezerka** [comment] 2020-01-06 20:21
I was able to reproduce the problem. My setup is simple - single machine with dockers, where mosquitto + auth plugin is running in one docker container, the auth service, written in go, runs in another container. I'm sure it can be reproduced by anybody who tries it, nothing complex to set up.

I first tried to test my auth service independently from fake client, which generated "mosquitto-auth-like" calls (user, superuser, acl), to be sure the consumption of file descriptors isn't on auth service side. It was ok.

Then I found the issue and tried what @wattanakorn495 posted here. I'm talking about this commit in his/her fork: wattanakorn495/mosquitto-go-auth@4f0b3d280314a6a0a3477af16ef94dab450c2d94. It contains more touches (super user checking, Dockerfile additions). So I finally created this commit in my fork: mnezerka/mosquitto-go-auth@13f2b40dd0f90d92876c18749f545da9a91f2921. It seems it helped, my server is running more than two days under load and number of file descriptors is constant.

It is sad that I didn't found any bug in your code, I see your are closing Body correctly and I don't see anything smart on moving Client instance up and reusing it for all http requests. That's probably a reason why people have it in forks instead of coming with PR.

**Comment by iegomez** [comment] 2020-01-06 20:35
Thanks for the detailed description. And I agree, it doesn't make sense that the connections leak, but if it's presenting a real problem to users such as yourself then I'll gladly accept a PR with the mentioned change if you're willing to take the time.

**Closed** 2020-01-10 14:00 UTC
