### ISSUE TITLE
Using only Files backend for ACL with identity from TLS certificate

### ISSUE THREAD

**Issue by jakubondrus** [iegomez/mosquitto-go-auth#165] opened 2021-04-03 13:07 UTC
Hi, 

I was trying to test this plugin by using identity from TLS certificate as user and clientId with files registered for password and acl checks. What I found out is, that if there was `topic #` in ACL file with non-exiting user from password file, permission would be granted to any user trying to access any topic. 

![acl peter](https://user-images.githubusercontent.com/61357983/113479872-b2734680-9491-11eb-9cb3-8e3884aae29c.png)

![acl debug](https://user-images.githubusercontent.com/61357983/113479882-bbfcae80-9491-11eb-919a-f70579f1167c.png)

After checking source codes I think I understand why it's happening. I would like to ask, whether there is any way to use ACL files like mosquitto's default ACL files, so this would not happen or if only way is to modify current plugin implementation. 
(I am currently testing it on files, but I later intend to add http api as another source for ACL checks)

JO

**Comment by iegomez** [comment] 2021-04-03 15:41
I'm not sure what's the issue here, setting a general permission for all users will indeed grant them access, that's expected.
What are you trying to achieve?

**Comment by jakubondrus** [comment] 2021-04-03 15:54
I am trying to achieve that when setting
`user Peter`
`topic #`
it will be only applied to Peter like with mosquitto's acl. But when Peter is not listed in password file (because I use certs for authentication) this rule is set as general permission. I would like to find out, whether there is way to avoid this behaviour without modifying plugin code. Or possibly use mosquitto's acl in combination with http backend (config file says "If an auth_plugin is used as well as acl_file, the auth_plugin check will be made first." but http calls doesn't happen if I turn on mosquitto ACL).

**Comment by iegomez** [comment] 2021-04-03 17:34
What version are you using? There used to be a bug where a missing user would result in their ACL rules applied to the previous user or, if it was the first one, to the general rules. That should be fixed, but if you're seeing that behavior, that would be  bug.
I'm currently working on some Files changes, so if you can provide evidence and a way to reproduce the issue, I can fix it long with that work.

**Comment by iegomez** [comment] 2021-04-03 17:45
One thing Iḿ curious about is the TLS auth you mentioned, the plugin doesn't offer such auth method, how are you accomplishing it?

**Comment by jakubondrus** [comment] 2021-04-03 17:54
> One thing Iḿ curious about is the TLS auth you mentioned, the plugin doesn't offer such auth method, how are you accomplishing it?

I am using mosquitto's `use_identity_as_username true` which takes identity from certificate provided by client and uses it as username (and could be also set to be used as clientId).



> What version are you using? There used to be a bug where a missing user would result in their ACL rules applied to the previous user or, if it was the first one, to the general rules. That should be fixed, but if you're seeing that behavior, that would be bug.
> I'm currently working on some Files changes, so if you can provide evidence and a way to reproduce the issue, I can fix it along with that work.

I used acl file as posted above (only 2 lines with `user Peter` and `topic #`) and used it as single backend, while using empty password file.

**Comment by iegomez** [comment] 2021-04-03 17:59
Cool, thanks for the details! I'll take a look soon.

**Comment by iegomez** [comment] 2021-04-03 22:58
Ok, @jakubondrus, here's a PR that tackles your issue along with the original intent of adding a files-like ACL check for JWT: https://github.com/iegomez/mosquitto-go-auth/pull/166
Would yo be able to checkout that specific branch and test it before I merge it?

Thanks again for your report and support.

Cheers!

**Comment by jakubondrus** [comment] 2021-04-04 00:06
> Ok, @jakubondrus, here's a PR that tackles your issue along with the original intent of adding a files-like ACL check for JWT: #166
> Would yo be able to checkout that specific branch and test it before I merge it?
> 
> Thanks again for your report and support.
> 
> Cheers!

I will take a look at it tomorrow. Thanks for making time to look into this.

**Comment by iegomez** [comment] 2021-04-04 00:10
Sorry that I didn't mention it, but you'll have to explicitly set the Files backend to only check ACLs, i.e.:
```
auth_opt_files_register acl
```

I'll wait for you response on how that went. Thanks again!

**Comment by jakubondrus** [comment] 2021-04-04 13:00
It seems, like it's granting access to topics to everyone now. 
ACL
![image](https://user-images.githubusercontent.com/61357983/113509433-d304d480-9555-11eb-8d28-fe130a6fa212.png)
Left is Klient2 and right Klient
![image](https://user-images.githubusercontent.com/61357983/113509467-07789080-9556-11eb-8b2e-66760c706a8e.png)
Config fle
![image](https://user-images.githubusercontent.com/61357983/113509508-4a3a6880-9556-11eb-8dc2-1cc040072522.png)

**Comment by iegomez** [comment] 2021-04-04 22:57
Thanks again, I'll do some testing with you exact use case to see what might be going on.

**Comment by iegomez** [comment] 2021-04-09 00:21
Hey, sorry I haven't had time to test this yet, I'll try to take a look tomorrow.

**Comment by iegomez** [comment] 2021-04-10 02:22
Ok, @jakubondrus , there was indeed a subtle bug but luckily I was able to identify and fix it in https://github.com/iegomez/mosquitto-go-auth/pull/166/commits/530fb7ee2057d09ffe65069b8ecef5f4c6fad932. I added a test for it just in case, and I think now you should be able to run that branch for your case successfully.

Again, sorry for the delay and please let me know how it goes this time. If you find no issues, then I'll merge it ASAP.

:bow:

**Comment by jakubondrus** [comment] 2021-04-10 14:22
Hi, thanks again for making time to look into this. But I still can't make it work. Since I am not sure, whether I understand how to use this plugin correctly, so I recorder video showing my use of this plugin. Basically expected behaviour is that "Klient" will be able to push/sub anywherere, meanwhile Klient2 should be able to read only clients/Klient topic and writo to clients/Klient2.
https://drive.google.com/file/d/1IFVuB2irQPQfUcac9LvZ06HQ2sXFZ-vL/view

**Comment by iegomez** [comment] 2021-04-10 16:24
Wow, thanks for the very detailed video! I'll look into it, and again sorry that it's not working for you.

I'm wondering something though: you are already using `use_identity_as_username` for authentication, and Mosquitto provides static files authorization out of the box. Does it not support checking ACLs only and that's why you had to resort to using the plugin for auth? Don't get me wrong, even if it did and your use case was covered by it, I'm thankful that you gave the plugin a try and surfaced some bugs so I may fix them. I'm just curious about it since I haven't used Mosquitto in a long while and I'm afraid I may be out of date on its capabilities.

**Comment by jakubondrus** [comment] 2021-04-10 16:35
I want to use files for more "static" users and permissions and http api for more dynamic ones. That's why I want to combine them. However, when I used build-in acls combined with http api, http api was never called even if files didn't give permission for topic. This is why I would like to use plugin for both cases.

**Comment by iegomez** [comment] 2021-04-10 16:38
Ah, gotcha. And yes, if you use Mosquitto's static files auth, then it won't forward any requests to a plugin.
Well, I hope to have good news for you soon after taking a better look into the issue.

Cheers!

**Comment by iegomez** [comment] 2021-04-24 15:41
@jakubondrus I just rewatched your video and realized you're using SYS topics. I'm not really sure, haven't read the docs thoroughly, but aren't those supposed to be read-only broker information messages that any client can subscribe to?

**Comment by jakubondrus** [comment] 2021-04-24 16:06
Example ACL file in mosquitto git repo has it specificaly listed in ACL. Since they have it there I assumed it isn't "public" for all clients. I am not sure about this one tho. But if we ignore this topic, there is also situation where Klient2 published something to cli topic, while ACL had only pattern clients/%c listed to write. That means, that Klient2 is supposed to be able to publish only into clients/Klient2.

**Comment by iegomez** [comment] 2021-04-24 16:22
@jakubondrus Are you sure youŕe not allowing anonymous access at mosquitto's conf or something similar?
I just added this test to the suite, which checks that `Klient2` isn't able to write to topic `cli`, and it passes correctly: https://github.com/iegomez/mosquitto-go-auth/pull/166/commits/1147717612403cb4b885fee21150fe819f6eed91

**Comment by jakubondrus** [comment] 2021-04-24 16:47
I think this is config file I used when testing it (deleted commented lines). Allow anonymous should default to false unless there are no listeners defined. 

[conf.txt](https://github.com/iegomez/mosquitto-go-auth/files/6370162/conf.txt)

**Comment by iegomez** [comment] 2021-04-25 01:56
Yeah, it should be the default. I haven't run your example conf (thanks for providing it by the way, :bowing_woman: ), I don't really have the time to do more poking right now (I haven't really run or used mosquitto in a very long while), sorry for that. Tests with your case are passing and it looks to me like there's an external problem. Probably a couple of `printf` here and there to see what's being granted and what not should shed some light, so I encourage you to clone this branch and do some checking.

Sorry for an unsatisfactory answer, that's the best I can do for now. I'll be here to discuss any of your findings, so feel free to ping me again in that matter.

Again, sorry, and cheers!

**Comment by jakubondrus** [comment] 2021-04-26 08:05
No problem. Will take look at it and if I find something new I will get back to you. Thanks for looking into it.

**Comment by iegomez** [comment] 2021-07-31 00:15
Hey, @jakubondrus, I'm closing this issue for inactivity. Ping me if you want to further discuss it.

Cheers!

**Closed by iegomez** 2021-07-31 00:15 UTC
