### ISSUE TITLE
Error: An auth_opt_ option exists in the config file without an auth_plugin

### ISSUE THREAD

**Issue by mrdc** [iegomez/mosquitto-go-auth#125] opened 2020-11-15 16:10 UTC
Hello,

I'm having the issue with the plugin (v1.3.1) - on start mosquitto fails with these errors:
```
1605455392: Loading config file /etc/mosquitto/conf.d/mosquitto-go-auth.conf
1605455392: Error: An auth_opt_ option exists in the config file without an auth_plugin.
1605455392: Error found at /etc/mosquitto/conf.d/mosquitto-go-auth.conf:1.
1605455392: Error found at /etc/mosquitto/mosquitto.conf:16.
```

When I remove  `mosquitto-go-auth.conf` from `conf.d` mosquitto fails with this error: `FATA[2020-11-15T16:04:15Z] backends error` That's expected, because no config is provided, but it's not clear why it fails with correct backend settings in `/etc/mosquitto/conf.d/mosquitto-go-auth.conf`

Triple checked everything and have no idea why it fails.

**/etc/mosquitto/mosquitto.conf:**
```
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto.pid
auth_plugin /etc/mosquitto/mosquitto-go-auth/go-auth.so
allow_anonymous false
password_file /etc/mosquitto/psw
acl_file /etc/mosquitto/acls
persistence true
persistence_location /var/lib/mosquitto/
#log_type all
log_dest file /var/log/mosquitto/mosquitto.log
include_dir /etc/mosquitto/conf.d
```

**/etc/mosquitto/conf.d/mosquitto-go-auth.conf:**
```
auth_opt_backends files
auth_opt_cache true
auth_opt_cache_reset true
auth_opt_auth_cache_seconds 30
auth_opt_acl_cache_seconds 30
auth_opt_log_file /var/log/mosquitto/mosquitto.log
auth_opt_password_path /etc/mosquitto/psw_go_auth
auth_opt_acl_path /etc/mosquitto/acls
```

**/etc/mosquitto/psw_go_auth:**
`
user:PBKDF2$sha512$100000$.......$.......
`

Raspbian Buster 
Mosquitto 1.6.12
Mosquitto-go-auth 1.3.1

**Comment by iegomez** [comment] 2020-11-16 01:46
Hey, @mrdc! I was away during the weekend so couldn't check, but will take a look during the week. Thanks for reporting it.
Cheers!

**Comment by pikkuhanuristi** [comment] 2020-11-20 12:38
Hey, 
I faced exactly the same problem!
I'm mosquitto rookie, so might it be configuration mistake?

1605875838: Loading config file /etc/mosquitto/conf.d/listener_mqtt.conf
1605875838: Loading config file /etc/mosquitto/conf.d/mosquitto-go-auth.conf
1605875838: Error: An auth_opt_ option exists in the config file without an auth_plugin.
1605875838: Error found at /etc/mosquitto/conf.d/mosquitto-go-auth.conf:1.
1605875838: Error found at /etc/mosquitto/mosquitto.conf:990.

/etc/mosquitto/mosquitto.conf
`auth_plugin /home/username/projects/mosquitto/mosquitto-go-auth-1.3.0/go-auth.so`

/etc/mosquitto/conf.d/mosquitto-go-auth.conf
`auth_opt_backends files
auth_opt_log_level debug
auth_opt_log_dest file
auth_opt_log_file /var/log/mosquitto/mosquitto.log
auth_opt_password_path /etc/mosquitto/aclfile.example
auth_opt_acl_path /etc/mosquitto/pwfile.example`

mosquitto-1.6.10
mosquitto-go-auth-1.3.0

**Comment by iegomez** [comment] 2020-11-25 23:18
@pikkuhanuristi @mrdc The problem is you're setting `auth_plugin` in the general `mosquitto.conf` file insteaf of the plugin's `conf.d/go-auth.conf` one (or wherever/whatever you placed and named it). 
Not sure why Mosquitto parses confs in that particular order, but I was able to reproduce the issue and fix it by just moving the `auth_plugin` option to the plugin's file.

**Comment by iegomez** [comment] 2020-11-25 23:54
I believe this changed in Mosquitto's 1.5.5 version, so the Readme instructions are being fixed in https://github.com/iegomez/mosquitto-go-auth/pull/116.

**Closed** 2020-11-27 01:54 UTC

**Comment by mrdc** [comment] 2020-11-27 14:03
@iegomez 
Hello, thanks for info.
BTW, it's also a good idea to specify in readme that `password_file` option should be disabled in `mosquitto.conf` when using files backend, otherwise mosquitto also uses this file together with `psw_go_auth` file in my case.
