### ISSUE TITLE
Checksum error

### ISSUE THREAD

**Issue by lithium3d** [iegomez/mosquitto-go-auth#41] opened 2020-01-05 20:49 UTC
I'm having the next problem:

go build -buildmode=c-archive go-auth.go
go: verifying github.com/go-stack/stack@v1.8.0/go.mod: checksum mismatch
        downloaded: h1:G7mAYYxgmS0lVkHyy2hEOLQCFB0DlQFTMLWggykrydY=
        go.sum:     h1:v0f6uXyyMGvRgIKkXu+yp6POWl0qKG85gN/melR3HDY=
make: *** [Makefile:2: all] Error 1

Any idea?

**Comment by iegomez** [comment] 2020-01-06 19:06
Sorry, I just tried a fresh install locally and it compiles correctly, I'm afraid I'm not able to reproduce this.

**Comment by lithium3d** [comment] 2020-01-06 22:02
I made a full new install of ubuntu, I got a different error now:

go build -buildmode=c-shared -o go-auth.so
# github.com/iegomez/mosquitto-go-auth
/usr/bin/ld: $WORK/b001/_x003.o: in function `mosquitto_auth_acl_check':
auth-plugin.c:(.text+0x3ec): undefined reference to `mosquitto_client_id'
/usr/bin/ld: auth-plugin.c:(.text+0x3f8): undefined reference to `mosquitto_client_username'
collect2: error: ld returned 1 exit status
make: *** [Makefile:3: all] Fout 2

**Comment by lithium3d** [comment] 2020-01-06 22:03
> Sorry, I just tried a fresh install locally and it compiles correctly, I'm afraid I'm not able to reproduce this.

This was probably an aftermath of a wrong installation...

**Comment by iegomez** [comment] 2020-01-06 22:17
Did you export the needed flags for compiling the plugin for mosquitto versions 1.5 and up? If you did so and installed mosquitto from apt, did you install the mosquitto-dev package too?

**Comment by lithium3d** [comment] 2020-01-07 14:13
> Did you export the needed flags for compiling the plugin for mosquitto versions 1.5 and up? If you did so and installed mosquitto from apt, did you install the mosquitto-dev package too?

No the mosquitto-dev was not installed. I did the flags, I just installed it and run make again but still the same error

**Comment by iegomez** [comment] 2020-01-07 14:15
Then I'd recommend uninstalling mosquitto and mosquitto-dev, and then building it manually. You may follow the instructions from the readme, just change mosquitto version accordingly.

**Comment by lithium3d** [comment] 2020-01-07 14:16
Whats the best way to get rid of everything?

**Comment by iegomez** [comment] 2020-01-07 14:19
I think `sudo apt remove --purge mosquitto-dev mosquitto` should be enough, but I can't say for sure.

**Comment by lithium3d** [comment] 2020-01-07 14:21
Do I need to destroy the go-auth dir?

**Comment by iegomez** [comment] 2020-01-07 14:30
You mean your clone of this repo? No, it's not needed. I'm just suggesting you get rid of mosquitto itself and rebuild it so the plugin may find the necessary dependencies.

**Comment by lithium3d** [comment] 2020-01-07 15:15
Still the same problem..

**Comment by iegomez** [comment] 2020-01-07 15:41
Check that `mosquitto_broker.h` is present at `/usr/local/include`. If it's not, then you should reinstall mosquitto as something isn't right; if it is, maybe you exported the flags in a different terminal than that where you're building the plugin.

**Comment by lithium3d** [comment] 2020-01-07 20:04
> Check that `mosquitto_broker.h` is present at `/usr/local/include`. If it's not, then you should reinstall mosquitto as something isn't right; if it is, maybe you exported the flags in a different terminal than that where you're building the plugin.

I have followed your instructions, but I'm still getting the same error. Just irritating

**Comment by iegomez** [comment] 2020-01-07 20:13
I'm sorry about that, but it's kind of difficult helping you to locate the issue from a distance and I'm running out of general ideas.

**Comment by iegomez** [comment] 2020-01-10 13:58
I'll close this for now, just send me a message if there's any news.

**Closed by iegomez** 2020-01-10 13:58 UTC
