### ISSUE TITLE
Files backend `topic` cannot contain <space character>.

### ISSUE THREAD

**Issue by mcr-ksh** [iegomez/mosquitto-go-auth#154] opened 2021-02-18 13:04 UTC
Hi,

there is a problem that MQTT standard allows whitespace characters, while the backend files.go does not support that due to the strings.Fields(line) splitting.

I used a workaround in my local copy:
`                                if len(lineArr) == 2 {
                                        aclRecord.Topic = strings.Replace(lineArr[1], "%20", " ", -1)
                                        aclRecord.Acc = MOSQ_ACL_READWRITE
                                } else {
                                        aclRecord.Topic = strings.Replace(lineArr[2], "%20", " ", -1)
`

I think this should be fixed properly.

Best,
CK

**Comment by PierreF** [comment] 2021-02-21 20:29
Hi,

thanks for the report. You solution also reply on using "%20" in the acl file instead of a real whitespace, isn't it ?

I've created a PR that fix it without needs to escape the whitespace (which is closer to what Mosquitto does, which is the format we said to support in our README). It however does not support multiple consecutive whitespaces in topic. Is it something you need ?

**Comment by mcr-ksh** [comment] 2021-02-22 09:01
Hi PierreF,

my solution is just a "hack" or workaround. Unfortunately we need multiple consecutive whitespaces.

Best,
CK

**Comment by iegomez** [comment] 2021-02-26 03:32
Hi, @mcr-ksh! Thanks for reporting this issue and sorry for not responding earlier, I've been having some issues with my personal machine and I don't like to use (nor I have setup correctly) my work one for personal development.

I see that @PierreF (sorry for not reviewing the other PRs yet, I have the same stated reason and having returned to work this week to blame for that) has already started working on this and I'll give it a look to see if I can give him a hand so we get this implemented ASAP: it surely is something that needs quick attention as it diverges from what Mosquitto's static files auth offers.

It's quite late here right now, so I'll try my best to tackle it tomorrow afternoon.

Cheers!

**Comment by iegomez** [comment] 2021-02-26 21:28
I just realized we also lack support for denying topics, i.e. `pattern deny <topic>`. I'll start to work on both concerns, but it'll obviously take some more time given the addition.

**Comment by iegomez** [comment] 2021-02-26 23:19
Ok, here's my take on the issue: https://github.com/iegomez/mosquitto-go-auth/pull/157
I still need to add tests to ensure it works as intended, but the logic to cover both cases is there. I'll add test cases as soon as I can.

**Comment by iegomez** [comment] 2021-03-05 21:20
@mcr-ksh @PierreF Merged and released: https://github.com/iegomez/mosquitto-go-auth/releases/tag/1.4.3

**Closed** 2021-03-12 02:52 UTC
